(function(){'use strict';
const $=id=>document.getElementById(id),T=window.THREE,C=window.RaceCore;
try{
 let state=C.create(),input={},options={laps:2,difficulty:'normal'},quality='high',sound=true,inspect=false,cameraMode=0,elapsed=0,last=performance.now(),oldPhase='',toastTimer=0,frames=0,metricStart=performance.now(),audio=null,wind=null;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let touch=matchMedia('(pointer: coarse)').matches||innerWidth<980;
 if(touch)document.body.classList.add('touch-enabled');
 const scene=new T.Scene();scene.background=new T.Color('#a5bcc1');scene.fog=new T.Fog('#a5b9b7',110,430);
 const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;$('world').appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.09,720);
 scene.add(new T.HemisphereLight('#eff3e0','#60796b',2.3));
 const sun=new T.DirectionalLight('#ffe1a4',3.1);sun.position.set(-40,58,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-28,right:28,top:29,bottom:-29,near:1,far:160});sun.shadow.normalBias=.035;sun.shadow.bias=-.00015;scene.add(sun,sun.target);
 const rim=new T.DirectionalLight('#d5eff4',1.05);rim.position.set(30,12,-50);scene.add(rim);
 const skyMat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 v;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1)),f.x),f.y);}void main(){vec3 d=normalize(v);float h=max(0.,d.y);vec3 c=mix(vec3(.84,.78,.64),vec3(.32,.57,.69),pow(h,.48));vec2 uv=d.xz/max(.07,d.y)*1.8;float n=noise(uv)*.5+noise(uv*2.1)*.26+noise(uv*4.3)*.14;float cloud=smoothstep(.46,.68,n)*smoothstep(.015,.18,d.y);c=mix(c,vec3(.92,.9,.80),cloud*.76);vec3 sd=normalize(vec3(-.7,.35,.3));float s=max(0.,dot(d,sd));c+=vec3(.24,.14,.04)*pow(s,32.);gl_FragColor=vec4(c,1.);}' });scene.add(new T.Mesh(new T.SphereGeometry(600,24,16),skyMat));
 const world=window.RaceWorld.build(scene),models=[];
 for(let id=0;id<6;id++){
  const m=window.RaceCat.make(scene,id),p=m.parts;
  for(const part of [p.head,p.tail,p.ribbon,...p.legs.flatMap(l=>[l.upper,l.lower,l.paw])])window.RaceWorld.bake(part);
  window.RaceWorld.bake(p.body,new Set([p.head,p.tail,p.ribbon,...p.legs.flatMap(l=>[l.upper,l.lower,l.paw])]));
  window.RaceWorld.bake(m.bike.bike,new Set([...m.bike.tires,m.bike.crank]));for(const w of m.bike.tires)window.RaceWorld.bake(w);window.RaceWorld.bake(m.bike.crank);
  models.push(m);
 }
 const leaderRows=[];for(let i=0;i<6;i++){const row=document.createElement('div');row.className='leader-row';const rank=document.createElement('em'),dot=document.createElement('i'),name=document.createElement('b');row.append(rank,dot,name);$('leaderboard').append(row);leaderRows.push({row,rank,dot,name});}
 const sparkCount=130,sparkPos=new Float32Array(sparkCount*3),sparkColor=new Float32Array(sparkCount*3),sparks=[];for(let i=0;i<sparkCount;i++){sparkPos[i*3+1]=-100;const c=new T.Color(i%3?'#f4bc70':'#85e4e2');sparkColor.set([c.r,c.g,c.b],i*3);sparks.push({life:0,vx:0,vy:0,vz:0});}
 const sparkGeo=new T.BufferGeometry();sparkGeo.setAttribute('position',new T.BufferAttribute(sparkPos,3));sparkGeo.setAttribute('color',new T.BufferAttribute(sparkColor,3));const sparkMesh=new T.Points(sparkGeo,new T.PointsMaterial({size:.1,vertexColors:true,transparent:true,opacity:.86,depthWrite:false}));sparkMesh.frustumCulled=false;scene.add(sparkMesh);
 const marks=[],markGeo=new T.BufferGeometry(),markPos=new Float32Array(160*6),markMesh=new T.LineSegments(markGeo,new T.LineBasicMaterial({color:'#272e29',transparent:true,opacity:.44}));markGeo.setAttribute('position',new T.BufferAttribute(markPos,3));scene.add(markMesh);markMesh.frustumCulled=false;let markIndex=0,previousMark=null;
 function playTone(f,d=.15,volume=.05){if(!sound)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type='sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(t+d+.02);}catch{sound=false;$('sound').textContent='音效 关';}}
 function message(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1700);}
 function format(t){if(t===null||!Number.isFinite(t))return '—';const min=Math.floor(t/60),sec=Math.floor(t%60),cs=Math.floor((t%1)*100);return String(min).padStart(2,'0')+':'+String(sec).padStart(2,'0')+'.'+String(cs).padStart(2,'0');}
 const heldControls=new Map();
 function syncInput(){input={};for(const action of heldControls.values())input[action]=true;}
 function clear(){heldControls.clear();input={};document.querySelectorAll('.held').forEach(el=>el.classList.remove('held'));}
 function newRace(){clear();inspect=false;state=C.create(options);C.start(state);cameraMode=0;snapCamera=true;oldPhase='';$('inspect').textContent='近看小橘';playTone(440,.18);}
 function menu(){clear();state=C.create(options);snapCamera=true;oldPhase='';inspect=false;$('inspect').textContent='近看小橘';}
 $('start').onclick=newRace;$('restart').onclick=newRace;$('restart-paused').onclick=newRace;$('return-menu').onclick=menu;$('exit').onclick=menu;
 function pause(){C.pause(state);clear();} $('pause').onclick=pause;$('resume').onclick=pause;
 $('inspect').onclick=()=>{inspect=!inspect;snapCamera=false;$('inspect').textContent=inspect?'回到整车':'近看小橘';};
 $('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'音效 开':'音效 关';$('sound').setAttribute('aria-pressed',String(sound));if(sound)playTone(880);};
 $('quality').onclick=()=>{quality=quality==='high'?'smooth':'high';renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?1.6:1));renderer.shadowMap.enabled=quality==='high';$('quality').textContent=quality==='high'?'画质 高':'画质 流畅';};
 for(const b of document.querySelectorAll('[data-laps]'))b.onclick=()=>{options.laps=Number(b.dataset.laps);document.querySelectorAll('[data-laps]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));};
 for(const b of document.querySelectorAll('[data-difficulty]'))b.onclick=()=>{options.difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));};
 function useNitro(){if(!C.boost(state))message(state.riders[0].boost>0?'正在冲刺':'漂移蓄满气，就有氮气');else playTone(330,.3,.045);}
 $('nitro-button').onclick=useNitro;$('touch-boost').onclick=useNitro;function nextCamera(){cameraMode=(cameraMode+1)%3;snapCamera=false;message(['追逐镜头','近距离追逐','侧后跟拍'][cameraMode]);}$('camera').onclick=nextCamera;
 const keyMap={ArrowUp:'forward',KeyW:'forward',ArrowDown:'brake',KeyS:'brake',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ShiftLeft:'drift',ShiftRight:'drift',KeyJ:'jump'};
 addEventListener('keydown',e=>{if(keyMap[e.code]){e.preventDefault();if(['racing','countdown'].includes(state.phase)){heldControls.set(e.code,keyMap[e.code]);syncInput();}}if(e.repeat)return;if(e.code==='Space'){e.preventDefault();if(state.phase==='menu')newRace();else useNitro();}if(e.code==='KeyR')C.recover(state);if(e.code==='KeyC'&&state.phase==='racing')nextCamera();if(e.code==='Escape'||e.code==='KeyP')pause();});
 addEventListener('keyup',e=>{if(keyMap[e.code]){e.preventDefault();heldControls.delete(e.code);syncInput();}});
 addEventListener('blur',()=>{if(['racing','countdown'].includes(state.phase))C.pause(state);clear();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){if(['racing','countdown'].includes(state.phase))C.pause(state);clear();}});
 for(const b of document.querySelectorAll('[data-control]')){const control=b.dataset.control;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(['racing','countdown'].includes(state.phase)){heldControls.set('pointer:'+e.pointerId,control);syncInput();b.classList.add('held');}});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>{heldControls.delete('pointer:'+e.pointerId);syncInput();b.classList.toggle('held',[...heldControls.values()].includes(control));});}
 function result(){const order=C.order(state),rank=order.findIndex(r=>r.id===0)+1;$('medal').textContent=String(rank).padStart(2,'0');$('result-title').textContent=rank===1?'小橘夺冠！':'风里跑过，第 '+rank+' 名';$('result-note').textContent='用时 '+format(state.riders[0].finishTime)+' · 最佳单圈 '+format(state.bestLap);$('result-table').replaceChildren();for(let i=0;i<order.length;i++){const r=order[i],row=document.createElement('div');row.className='result-row'+(r.id===0?' me':'');const n=document.createElement('span'),name=document.createElement('b'),t=document.createElement('time');n.textContent=String(i+1).padStart(2,'0');name.textContent=r.name;t.textContent=r.finished?format(r.finishTime):'尚未完赛';row.append(n,name,t);$('result-table').append(row);}playTone(rank===1?1047:523,.55);}
 function ui(){const menu=state.phase==='menu';document.body.classList.toggle('racing',!menu);$('lobby').hidden=!menu;$('cat-tag').hidden=!menu;$('hud').hidden=menu;$('pause-overlay').hidden=state.phase!=='paused';$('result').hidden=state.phase!=='result';$('touch').hidden=!touch||!['racing','countdown'].includes(state.phase);if(state.phase==='result'&&oldPhase!=='result')result();oldPhase=state.phase;}
 const mapCtx=$('map').getContext('2d');
 function map(){const ctx=mapCtx;ctx.clearRect(0,0,360,280);const x=v=>25+(v+212)*1.16,z=v=>18+(v+177)*.98;ctx.beginPath();C.track.pts.forEach((p,i)=>i?ctx.lineTo(x(p.x),z(p.z)):ctx.moveTo(x(p.x),z(p.z)));ctx.lineWidth=10;ctx.lineJoin='round';ctx.strokeStyle='#c6caba4d';ctx.stroke();ctx.lineWidth=3;ctx.strokeStyle='#d8dcca';ctx.stroke();for(const r of [...state.riders.slice(1),state.riders[0]]){ctx.beginPath();ctx.arc(x(r.x),z(r.z),r.id===0?6:4,0,Math.PI*2);ctx.fillStyle=r.id===0?'#ffc46f':r.color;ctx.fill();if(r.id===0){ctx.lineWidth=2;ctx.strokeStyle='#fef5da';ctx.stroke();}}}
 function hud(){const r=state.riders[0];$('speed').textContent=Math.round(r.speed*3.6);$('rank').textContent=state.rank;$('lap').textContent=r.lap+' / '+state.laps;$('time').textContent=format(state.time);$('lap-time').textContent=state.bestLap===null?'珠江杯 · 六猫竞速':'最佳 '+format(state.bestLap);$('charge').style.width=r.charge+'%';$('charge-number').textContent=Math.floor(r.charge)+'%';$('charge-label').textContent=r.drifting?'漂移中 · 蓄气':'漂移蓄气';$('nitro-count').textContent='× '+r.nitro;$('nitro-button').classList.toggle('empty',r.nitro===0);$('speed-lines').classList.toggle('active',state.phase==='racing'&&r.boost>0&&!reduced);const f=((r.progress%C.L)+C.L)%C.L/C.L;$('zone').textContent=f<.31?'西关骑楼':f<.60?'沙面绿荫':f<.86?'珠江大桥':'木棉弯道';const order=C.order(state);order.forEach((r,i)=>{const v=leaderRows[i];v.row.classList.toggle('my',r.id===0);v.rank.textContent=i+1;v.dot.style.backgroundColor=r.color;v.name.textContent=r.name;});map();}
 let snapCamera=true,camHeading=C.at(-7).heading,hudT=0,worldT=0,lastCountdown=4;
 function position(dt){for(let i=0;i<6;i++){const r=state.riders[i],m=models[i];m.root.position.set(r.x,r.y+.08+r.jumpY,r.z);m.root.rotation.y=r.heading;m.root.rotation.z=-r.steer*Math.min(.32,r.speed*.012);window.RaceCat.animate(m,r,elapsed);}
 const r=state.riders[0],head=r.heading;camHeading=C.wrap(camHeading+C.wrap(head-camHeading)*(1-Math.exp(-dt*(r.drifting?4:7))));const p=new T.Vector3(r.x,r.y,r.z);let eye,look,fov;
 if(state.phase==='menu'){
  const portrait=innerWidth<480&&innerHeight>540,ang=head+(inspect?-.18:Math.sin(elapsed*.12)*.06);
  let local=inspect?new T.Vector3(1.12,2.31,-1.95):new T.Vector3(3.16,2.9,-4.38);if(portrait)local=inspect?new T.Vector3(.9,2.8,-2.9):new T.Vector3(2.8,3.05,-4.1);
  local.applyAxisAngle(new T.Vector3(0,1,0),ang);eye=p.clone().add(local);
  const target=inspect?new T.Vector3(.7,1.94,-.04):new T.Vector3(1.2,1.20,.1);if(portrait)target.set(0,.52,0);target.applyAxisAngle(new T.Vector3(0,1,0),ang);look=p.clone().add(target);fov=inspect?40:43;
 }else{
  const settings=[{x:0,y:3.65,z:6.4,look:5.5},{x:0,y:2.5,z:4.55,look:6},{x:3.5,y:2.7,z:4.8,look:3}],s=settings[cameraMode];const offset=new T.Vector3(s.x,s.y,s.z+(r.boost>0&&!reduced?.6:0)).applyAxisAngle(new T.Vector3(0,1,0),camHeading);eye=p.clone().add(offset);eye.y+=r.jumpY*.48;look=p.clone().add(new T.Vector3(0,1.25,-s.look).applyAxisAngle(new T.Vector3(0,1,0),camHeading));look.y+=r.jumpY*.38;fov=53+Math.min(7,r.speed*.18)+(r.boost>0&&!reduced?4:0);
 }
 const alpha=snapCamera?1:1-Math.exp(-dt*(state.phase==='menu'?3.5:8));camera.position.lerp(eye,alpha);camera.lookAt(look);camera.fov+=(fov-camera.fov)*alpha;camera.updateProjectionMatrix();snapCamera=false;
 // Hide opponents only while they intersect the near chase camera.
 for(let i=1;i<models.length;i++){const m=models[i],head=m.root.position.clone().add(new T.Vector3(0,1.6,0));m.root.visible=state.phase==='menu'||head.distanceTo(camera.position)>3.3;}
 sun.position.set(r.x-36,r.y+57,r.z+32);sun.target.position.set(r.x,r.y,r.z);
 }
 function effects(dt){const r=state.riders[0],active=state.phase==='racing'&&(r.drifting||r.boost>0||r.mini>0);for(let i=0;i<sparkCount;i++){const p=sparks[i];if(p.life<=0&&active&&Math.random()<.1&&!reduced){const side=Math.random()<.5?-1:1,xx=Math.cos(r.heading)*side*.14,zz=-Math.sin(r.heading)*side*.14;sparkPos[i*3]=r.x+xx+Math.sin(r.heading)*.85;sparkPos[i*3+1]=r.y+.22;sparkPos[i*3+2]=r.z+zz+Math.cos(r.heading)*.85;p.life=.24+Math.random()*.25;p.vx=Math.sin(r.heading)*3+side*Math.cos(r.heading)*2;p.vz=Math.cos(r.heading)*3-side*Math.sin(r.heading)*2;p.vy=Math.random()*1.5;}if(p.life>0){p.life-=dt;sparkPos[i*3]+=p.vx*dt;sparkPos[i*3+1]+=p.vy*dt;p.vy-=dt*6;sparkPos[i*3+2]+=p.vz*dt;}else sparkPos[i*3+1]=-100;}sparkGeo.attributes.position.needsUpdate=true;
 if(active&&r.drifting){const now=[r.x,r.y+.093,r.z];if(previousMark){markPos.set([...previousMark,...now],markIndex*6);markIndex=(markIndex+1)%160;markGeo.attributes.position.needsUpdate=true;}previousMark=now;}else previousMark=null;
 }
 function resize(){touch=matchMedia('(pointer: coarse)').matches||innerWidth<980;document.body.classList.toggle('touch-enabled',touch);ui();camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);snapCamera=true;}addEventListener('resize',resize);
 function frame(now){const dt=Math.min(.06,Math.max(0,(now-last)/1000));last=now;const frozen=state.phase==='paused'||state.phase==='result';if(!frozen)elapsed+=dt;C.step(state,input,dt);if(state.phase!==oldPhase)ui();for(const e of state.events){if(e.type==='go')playTone(880,.3);if(e.type==='hit')playTone(110,.09,.02);if(['mini','pad','nitro','lap','finish'].includes(e.type))message(e.text);if(e.type==='nitro')playTone(1320,.22);}
 if(state.phase==='countdown'){const number=Math.ceil(state.countdown);$('countdown').textContent=number;if(number!==lastCountdown){lastCountdown=number;playTone(440,.12);}}else $('countdown').textContent=state.phase==='racing'&&state.go>0?'GO!':'';
 if(!frozen){position(dt);effects(dt);worldT+=dt;if(worldT>.09){world.update(elapsed);worldT=0;}}
 hudT+=dt;if(hudT>.08){hud();hudT=0;}renderer.render(scene,camera);frames++;requestAnimationFrame(frame);}
 // Read-only diagnostics used to verify phase, race integrity, and render costs.
 window.__race={get state(){return JSON.parse(JSON.stringify(state));},get metrics(){return {fps:frames/((performance.now()-metricStart)/1000),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries};},get ready(){return true;}};
 $('loading').hidden=true;$('start').disabled=false;ui();position(1);hud();requestAnimationFrame(frame);
}catch(e){$('loading').hidden=true;$('fatal').hidden=false;$('error-detail').textContent=String(e);console.error(e);}
})();
