"""Collect the house data from the original film project into data/house.js (run by hand, not in CI).

Source project (author's machine): the floor-plan film project. Its four JSON files were produced by
reading the public-domain image "Sample Floorplan.jpg" (see ../THIRD_PARTY_NOTICES.md).
Usage: python3 tools/make-data.py <project-dir>
"""
import json, sys, shutil
from pathlib import Path

src = Path(sys.argv[1])
root = Path(__file__).resolve().parent.parent
plan = json.loads((src / 'data/plan.json').read_text())
derived = json.loads((src / 'data/derived-v2.json').read_text())
furniture = json.loads((src / 'data/furniture.json').read_text())
sun = json.loads((src / 'data/sun.json').read_text())

def r1(v):
    if isinstance(v, float): return round(v, 2)
    if isinstance(v, list): return [r1(x) for x in v]
    if isinstance(v, dict): return {k: r1(x) for k, x in v.items()}
    return v

house = {
    'source': 'Sample Floorplan.jpg (Boereck, 2006, Wikimedia Commons, public domain)',
    'image_px': plan['image_px'],
    'm_per_px': plan['m_per_px'],
    'wall_height_m': plan['wall_height_m'],
    'wall_bbox_px': [min(p[0] for w in plan['walls'] for p in w['outer']), min(p[1] for w in plan['walls'] for p in w['outer']),
                     max(p[0] for w in plan['walls'] for p in w['outer']), max(p[1] for w in plan['walls'] for p in w['outer'])],
    'walls': r1([{'outer': w['outer'], 'holes': w['holes']} for w in derived['walls_clean']]),
    'openings': [{k: o[k] for k in ('id', 'kind', 'exterior', 'horizontal', 'sill_m', 'head_m', 'rect_px')} for o in plan['openings']],
    'diagonal_windows': r1([{k: d[k] for k in ('id', 'a_px', 'b_px', 'quad_px', 'sill_m', 'head_m')} for d in derived['diagonal_windows']]),
    'doors': [{k: d[k] for k in ('id', 'exterior', 'horizontal', 'rect_px', 'swing', 'leaves', 'note', 'glazed', 'leafless') if k in d} for d in derived['doors']],
    'baseboards': r1(derived['baseboards']),
    'floor_zones': r1(derived['floor_zones']),
    'footprint_px': r1(derived['footprint_px']),
    'rooms': r1([{k: r[k] for k in ('name_zh', 'name_en', 'center_px', 'area_m2', 'polygon_px')} for r in plan['rooms']]),
    'furniture': [{k: f[k] for k in ('type', 'rect_px', 'back', 'h') if k in f} for f in furniture],
    'sun': {
        'place': sun['location']['name_zh'], 'assumed': sun['location']['assumed'], 'date': sun['date'], 'date_zh': sun['date_zh'],
        'sunrise': sun['sunrise'], 'sunset': sun['sunset'], 'noon_altitude_deg': sun['noon_altitude_deg'],
        'steps': [[s['min'], s['az'], s['alt']] for s in sun['steps']],
        'room_hours': {r['name']: r['hours_sun'] for r in sun['rooms']},
    },
}
out = root / 'data/house.js'
out.write_text('// Generated by tools/make-data.py from the film project data. Do not edit by hand.\nexport default ' + json.dumps(house, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
shutil.copyfile(src / 'input/floorplan.jpg', root / 'assets/floorplan.jpg')
print(out, out.stat().st_size, 'bytes;', len(house['walls']), 'walls,', len(house['furniture']), 'furniture rows')
