const test=require('node:test');
const assert=require('node:assert/strict');
const C=require('../src/race-core.js');
const tick=(s,input,seconds)=>{for(let t=0;t<seconds;t+=1/60)C.step(s,input,1/60);};
function active(options={}){const s=C.create(options);C.start(s);tick(s,{},3.4);assert.equal(s.phase,'racing');return s;}
function pilot(s,boost=true){const r=s.riders[0],n=C.nearest(r.x,r.z),p=C.at(n.s+7+r.speed*.36),err=C.wrap(Math.atan2(-(p.x-r.x),-(p.z-r.z))-r.heading),turn=Math.abs(C.wrap(C.at(n.s+15).heading-n.heading));if(boost&&r.nitro>0&&r.boost===0&&turn<.2&&r.speed>17)C.boost(s);return {forward:true,left:err>.035,right:err<-.035,brake:turn>.8&&r.speed>13,drift:turn>.48&&Math.abs(err)>.13};}
test('race options are bounded and the road closes continuously',()=>{const s=C.create({laps:-1,difficulty:'bogus'});assert.equal(s.laps,2);assert.equal(s.difficulty,'normal');const a=C.at(0),b=C.at(C.L-.001);assert.ok(Math.hypot(a.x-b.x,a.z-b.z)<.01);assert.ok(C.L>700&&C.L<850);});
test('countdown rejects movement and nitro',()=>{const s=C.create();C.start(s);const before=s.riders.map(r=>[r.x,r.z,r.speed]);tick(s,{forward:true,right:true},2);assert.deepEqual(s.riders.map(r=>[r.x,r.z,r.speed]),before);assert.equal(C.boost(s),false);assert.equal(s.time,0);});
test('throttle moves the player, braking stops, release preserves direction',()=>{const s=active();tick(s,{forward:true},1.4);assert.ok(s.riders[0].speed>9);const h=s.riders[0].heading;tick(s,{forward:true},.3);assert.ok(Math.abs(s.riders[0].heading-h)<1e-10);tick(s,{brake:true},1.5);assert.equal(s.riders[0].speed,0);});
test('left and right steer oppositely',()=>{const a=active(),b=active();tick(a,{forward:true},1);tick(b,{forward:true},1);const h=a.riders[0].heading;tick(a,{forward:true,left:true},.25);tick(b,{forward:true,right:true},.25);assert.ok(C.wrap(a.riders[0].heading-h)>0);assert.ok(C.wrap(b.riders[0].heading-h)<0);});
test('pause freezes countdown and every racer',()=>{const s=C.create();C.start(s);C.pause(s);const copy=JSON.stringify(s);tick(s,{forward:true},1);assert.equal(JSON.stringify(s),copy);C.pause(s);tick(s,{},3.4);C.pause(s);const racers=JSON.stringify(s.riders),time=s.time;tick(s,{forward:true},2);assert.equal(JSON.stringify(s.riders),racers);assert.equal(s.time,time);C.pause(s);assert.equal(s.phase,'racing');});
test('nitro is consumable, cannot stack or underflow, and raises speed',()=>{const a=active(),b=active();tick(a,{forward:true},2);tick(b,{forward:true},2);assert.equal(C.boost(a),true);assert.equal(C.boost(a),false);assert.equal(a.riders[0].nitro,0);tick(a,{forward:true},1);tick(b,{forward:true},1);assert.ok(a.riders[0].speed>b.riders[0].speed+3);tick(a,{},3);assert.equal(C.boost(a),false);});
test('drifting charges energy; releasing a real drift gives a short boost',()=>{const s=active();tick(s,{forward:true},1.5);tick(s,{forward:true,left:true,drift:true},.7);assert.ok(s.riders[0].charge>8);tick(s,{forward:true},.05);assert.ok(s.riders[0].mini>.5);});
test('guardrails prevent escape; recovery keeps progress and does not add gates',()=>{const s=active();tick(s,{forward:true,right:true},15);const r=s.riders[0];assert.ok(C.nearest(r.x,r.z).distance<C.track.width);assert.ok(r.collisions>0);const progress=r.progress,gate=r.gate;C.recover(s);assert.equal(r.progress,progress);assert.equal(r.gate,gate);assert.equal(r.speed,0);assert.ok(C.nearest(r.x,r.z).distance<.01);});
test('a long suspended frame cannot advance an entire lap',()=>{const s=active();tick(s,{forward:true},1);const before=s.riders[0].progress;C.step(s,{forward:true},90);assert.ok(s.riders[0].progress-before<5);assert.equal(s.riders[0].lap,1);assert.equal(s.riders[0].finished,false);});
test('jump lands, and holding the key cannot make the player fly',()=>{const s=active();tick(s,{forward:true,jump:true},.2);assert.ok(s.riders[0].jumpY>.3);tick(s,{forward:true,jump:true},1.5);assert.equal(s.riders[0].jumpY,0);tick(s,{forward:true},.1);tick(s,{forward:true,jump:true},.2);assert.ok(s.riders[0].jumpY>.3);});
test('player completes two legitimate laps against five independent cats; skilled input can win',()=>{const s=active({laps:2,difficulty:'normal'});for(let i=0;i<60*150&&s.phase!=='result';i++)C.step(s,pilot(s),1/60);assert.equal(s.phase,'result');assert.equal(s.rank,1);assert.ok(s.riders[0].gate>=16);assert.ok(s.riders[0].progress>=C.L*2);assert.ok(s.riders[0].finishTime>50&&s.riders[0].finishTime<100);assert.ok(s.bestLap>20);assert.equal(s.riders[0].collisions,0);assert.ok(new Set(s.riders.map(r=>Math.round(r.progress))).size>2);});
test('an idle player loses; computer racers finish without teleporting',()=>{const s=active({laps:1,difficulty:'hard'});tick(s,{},75);assert.equal(s.riders[0].finished,false);assert.equal(s.rank,6);assert.equal(s.finishOrder.length,5);for(const r of s.riders.slice(1)){assert.ok(r.finished);assert.ok(r.gate>=8);assert.ok(r.finishTime>25);assert.ok(r.progress<C.L+1);}});
test('reverse travel across start does not award a lap',()=>{const s=active({laps:1});const r=s.riders[0],p=C.at(10);Object.assign(r,{x:p.x,z:p.z,heading:C.wrap(p.heading+Math.PI),velocityHeading:C.wrap(p.heading+Math.PI),progress:10});tick(s,{forward:true},2);assert.ok(r.progress<10);assert.equal(r.gate,0);assert.equal(r.lap,1);assert.equal(r.finished,false);});
test('restart clears results, resources, progress and timers',()=>{const s=active({laps:3,difficulty:'hard'});tick(s,{forward:true},2);C.boost(s);C.reset(s);assert.equal(s.phase,'countdown');assert.equal(s.laps,3);assert.equal(s.difficulty,'hard');assert.equal(s.riders[0].nitro,1);assert.equal(s.time,0);assert.equal(s.riders[0].gate,0);assert.deepEqual(s.finishOrder,[]);});
function place(r,progress,lateral=0){const p=C.at(progress,lateral);Object.assign(r,{x:p.x,z:p.z,y:p.y,heading:p.heading,velocityHeading:p.heading,progress,speed:22});}
test('recrossing an earlier lap line cannot award another lap or best time',()=>{const s=active({laps:2});const r=s.riders[0];s.riders.slice(1).forEach(b=>b.finished=true);place(r,C.L+.04);Object.assign(r,{lap:2,gate:8,nextGate:C.L*9/8,heading:C.wrap(r.heading+Math.PI),velocityHeading:C.wrap(r.heading+Math.PI)});Object.assign(s,{time:38.1,lapTime:38,lastLapTime:38,bestLap:38});C.step(s,{forward:true},1/90);assert.ok(r.progress<C.L);assert.equal(r.lap,2);C.recover(s);tick(s,{forward:true},.4);assert.ok(r.progress>C.L);assert.equal(s.bestLap,38);assert.equal(s.lapTime,38);});
test('photo finishes use crossing time, not rider update order',()=>{const s=active({laps:1});s.time=40;s.riders.slice(2).forEach(b=>{b.finished=true;b.finishTime=99;});for(const [id,d,lane]of [[0,.18,-2],[1,.05,2]]){const r=s.riders[id];place(r,C.L-d,lane);Object.assign(r,{gate:7,nextGate:C.L});}C.step(s,{forward:true},1/90);assert.ok(s.riders[0].finished&&s.riders[1].finished);assert.ok(s.riders[1].finishTime<s.riders[0].finishTime);assert.deepEqual(s.finishOrder,[1,0]);assert.equal(s.rank,2);assert.equal(s.events.find(e=>e.type==='finish').text,'冲线！');});
test('legal travel at the inside hairpin keeps projected progress',()=>{const s=active();s.riders.slice(1).forEach(b=>b.finished=true);const r=s.riders[0];place(r,696.9,-7.5);r.heading=r.velocityHeading=0;const old=C.nearest(r.x,r.z).s,before=r.progress;C.step(s,{forward:true},1/90);const advanced=C.nearest(r.x,r.z).s-old;assert.ok(advanced>7);assert.ok(Math.abs(r.progress-before-advanced)<1e-8);});
